### ISSUE TITLE
Strangely Slow in Seoul, SouthKorea (might be error in anycast packet routing)

### ISSUE THREAD

**Issue by flyicn** [cdnjs/cdnjs#3395]
I wrote same issue in http://cdnjs.com/news. but i think i wrote the issuein wrong place. so i write this issue this place.

---

hi, i think it's strangely slow in SouthKorea, Seoul.

I heard that this CDN is sponsored by Cloudflare and I heard that Cloudflare has Datacenters in Seoul, Tokyo, Hongkong, and Singapore.

but when i ping the cdnjs.cloudflare.com, the ping is measured in 200ms. and when i tracert cdnjs.cloudflare.com, it says my packet is routed to U.S.A.

by the way, i also checked jsdelvier.net  which use cloudflare network.
when i ping the cdn.jsdelivr.net it says 2~3ms. and when i tracert cdn.jsdelvir.net, it says my packet is routed to Seoul, South Korea.

Can you check this issue why packet in SouthKorea is routed to U.S.A  not to Seoul(South Korea). or Tokyo(Japan) datacenter?

Geoip Lookup for xe-0-1-0.edge01.lax01.as13335.net / 206.223.123.156 is US.
http://www.geoiptool.com/en/?IP=206.223.123.156

![1 - vykjkm2](https://cloud.githubusercontent.com/assets/6879311/3280853/e657160a-f481-11e3-895b-41b6c051c4ba.png)
![2 - js6rpfy](https://cloud.githubusercontent.com/assets/6879311/3280854/e658e304-f481-11e3-8c92-8a9a7d6fd7ab.png)
![3 - vva8nfp](https://cloud.githubusercontent.com/assets/6879311/3280855/e659c440-f481-11e3-8567-fb2d2b5e0f87.png)
![4 - a9hitlh](https://cloud.githubusercontent.com/assets/6879311/3280856/e678fa36-f481-11e3-99b2-23847f2afe68.png)
Geoip Lookup for xe-0-1-0.edge01.lax01.as13335.net / 206.223.123.156 is US.
http://www.geoiptool.com/en/?IP=206.223.123.156

**Comment by premist** [comment]
Contacted CloudFlare support, their response is like this : 

> Currently we're awaiting an increase in capacity from a provider in Seoul. Currently traffic is temporarily re-routed.

> It seems as though your ISP prefers to transit you to LAX rather than somewhere else in Asia, due to where they have connectivity.

> Once the routes are re-introduced to Seoul after the capacity upgrade, traffic should again flow to there.

Seems like they have no notice on www.cloudflarestatus.com and have no timeframe estimation about when will this situation end.  

Another response from CF:

> "According to CloudFlare status page, however, Seoul is listed as 'Operational'. If status page shows false results, what's the point of having status page?"

> Because not all traffic is affected in that manner & only some customers may be in the situation. And, as Marty mentioned, it may also be an issue with how ISPs prefer to connect due to things like peering arrangements that they have (we don't have direct control over this).

> We will update you as soon as the circumstance changes on our end relative to the upgrades, and we hope that changes the behavior. Until then, however, there's nothing we can do to force it to route the way you want it to.

I guess on cdnjs.com side there's no way to bypass this issue caused by CloudFlare. Users in Korea will experience long latency problem until CloudFlare silently fix this issue and notifies no one.

**Comment by ryush00** [comment]
Perhaps, they don't have Seoul cdn.

**Comment by kiding** [comment]
Or perhaps they do, and people have been using it for a while until something happened, because it's listed in [CloudFlare Network Map](https://www.cloudflare.com/network-map), [CloudFlare Status](http://www.cloudflarestatus.com), and proved from the response of [Zendesk](https://www.zendesk.com) or the [trace of it](https://www.zendesk.com/cdn-cgi/trace). Notice the keyword `ICN` all over the place.

```
HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Thu, 29 Jan 2015 12:32:55 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d21017749711de493113f30d8d7fab2ea1422534774; expires=Fri, 29-Jan-16 12:32:54 GMT; path=/; domain=.zendesk.com; HttpOnly
Cache-Control: public, max-age=31557600000
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15768000
X-Download-Options: noopen
X-Xss-Protection: 0
X-Frame-Options: SAMEORIGIN
Vary: Accept-Encoding
Etag: W/"40404-1422483276000"
Last-Modified: Wed, 28 Jan 2015 22:14:36 GMT
Via: 1.1 vegur
CF-Cache-Status: HIT
Expires: Mon, 06 Feb 3015 12:32:55 GMT
CF-RAY: 1b057487587b09e8-ICN
```

**Comment by misol** [comment]
until now.. KT(1st ISP in Republic of Korea) route some traffics to LAX.

**Comment by kiding** [comment]
I guess no one cares about this anymore, but the problem is not resolved yet.

```
$ traceroute kiding.net
traceroute: Warning: kiding.net has multiple addresses; using 104.28.30.44
traceroute to kiding.net (104.28.30.44), 64 hops max, 52 byte packets
 1  192.168.x.x (192.168.x.x)  1.618 ms  1.654 ms  1.935 ms
 2  * * *
 3  125.145.14.189 (125.145.14.189)  91.979 ms  247.150 ms  199.960 ms
 4  125.144.30.61 (125.144.30.61)  85.092 ms
    125.144.20.109 (125.144.20.109)  51.960 ms
    125.144.30.61 (125.144.30.61)  82.114 ms
 5  125.144.23.41 (125.144.23.41)  85.463 ms  161.779 ms  94.796 ms
 6  125.144.81.106 (125.144.81.106)  100.306 ms
    125.144.80.86 (125.144.80.86)  64.882 ms  112.963 ms
 7  112.174.64.241 (112.174.64.241)  138.287 ms
    112.174.26.113 (112.174.26.113)  307.228 ms
    112.174.26.125 (112.174.26.125)  618.673 ms
 8  112.174.71.78 (112.174.71.78)  99.425 ms
    112.174.65.102 (112.174.65.102)  191.172 ms  187.023 ms
 9  112.174.93.245 (112.174.93.245)  646.662 ms
    112.174.93.249 (112.174.93.249)  410.778 ms
    112.174.93.245 (112.174.93.245)  79.284 ms
10  112.174.84.78 (112.174.84.78)  99.057 ms
    112.174.65.102 (112.174.65.102)  146.020 ms
    112.174.71.62 (112.174.71.62)  119.505 ms
11  112.174.87.238 (112.174.87.238)  179.749 ms
    112.174.87.118 (112.174.87.118)  191.091 ms
    112.174.93.245 (112.174.93.245)  329.600 ms
12  xe-0-1-0.edge01.lax01.as13335.net (206.223.123.156)  214.011 ms
    112.174.84.38 (112.174.84.38)  65.869 ms
    112.174.84.118 (112.174.84.118)  63.874 ms
13  112.174.87.250 (112.174.87.250)  204.320 ms  380.155 ms
    112.174.87.114 (112.174.87.114)  398.593 ms
14  104.28.30.44 (104.28.30.44)  209.222 ms
    xe-0-1-0.edge01.lax01.as13335.net (206.223.123.156)  239.075 ms
    104.28.30.44 (104.28.30.44)  214.486 ms
```

**Comment by kiding** [comment]
Finally we're seeing ICN from [cdnjs.com trace](http://cdnjs.com/cdn-cgi/trace). [My homepage](http://kiding.net/cdn-cgi/trace) still goes to LAX though. 

I'd like to ask what kind of CloudFlare plan cdnjs uses. I have a theory that ICN only responds to domains with paid plans.

**Comment by ryush00** [comment]
They fix the problem when only we complain it.

**Comment by PeterDaveHello** [comment]
@terinjokes Would you please help us answer @kiding ? Thanks

**Comment by ryankirkman** [comment]
Cdnjs has a special arrangement with Cloudflare. We certainly don't have a
free plan, if that answers your question.

**Comment by kiding** [comment]
Thanks for answering. Can I assume the special arrangement has been going on for a long while? If so, CloudFlare might be _increasing their capacity_ selectively by plans (which is understandable), but they're doing it very very slowly over the course of years, without any proper notice to customers, even to paid plans.

I guess the issue is resolved - at least for cdnjs for the time being. We don't know when the _capacity shortage_ will hit the fan again, or _stop hitting it at all_. I wonder if this issue will ever be mentioned on the status page, but in the mean time people are simply switching to Fastly.

**Comment by terinjokes** [comment]
@kiding When we open new locations, only certain plans may be announced for a short period of time, but we don't run locations as exclusively paid.

I connected via a VPN to an unrelated network in South Korea and found that I was consistently connecting to Hong Kong for your site. I don't know the interconnection details for that AS, but Hong Kong seemed to be the preferred route for those routers.

I've pinged our network team to see if they have any ideas in your specific AS's case.

**Comment by kiding** [comment]
@terinjokes Thanks for responding. Given that you're referring the issue _specific_, I assume CloudFlare is not recognizing this a generic widespread problem. I could easily find a handful of affected domains just by googling – here are the trace pages of them: [1](https://site5.com/cdn-cgi/trace) [2](https://nex32.net/cdn-cgi/trace) [3](https://speedwebdesigner.com/cdn-cgi/trace) [4](https://june.meson.kr/cdn-cgi/trace) [5](https://blog.hazard.kr/cdn-cgi/trace) [6](https://ilwar.com/cdn-cgi/trace) [7](https://sinoru.me/cdn-cgi/trace) [8](http://kudokun.me/cdn-cgi/trace) and so on.

The situation has become much better compared to the last year though, yet it's really still happening. Me and others have tried to appeal this problem for a while, but all we got was either _["Make a ticket"](https://twitter.com/cloudflare/status/547863538304184320)_ or _["It's temporary"](https://twitter.com/eastdakota/status/547854243689144320)_. I hope CloudFlare would finally acknowledge the problem – or at least [put a note somewhere](https://twitter.com/kid2ng/status/560409552940580865).

Well, the good thing is, at least it seems this problem is no longer the case of cdnjs, so this issue can be closed I guess. Though we would never know if/when the same thing is happening – or already happened.

**Comment by PeterDaveHello** [comment]
Do we still have problem/issue here? If not, I'll like to close this one since it's been a long time.

**Comment by misol** [comment]
It still happens, but it seems to be a problem of Cloudflare.

**Comment by ryush00** [comment]
Still happens. We can check connected edge at https://cdnjs.com/cdn-cgi/trace.

```
colo=LAX
```

I asked Cloudflare Support Center about performance degrade. And they answered that cdnjs should upgrade the plan to Business plan.


> We recently made some changes to our network routing that has effected how traffic is served for some of our Free and Pro customers. On our Free or Pro plans, we serve you locally with any ISP that interconnects with us, but not necessarily for traffic accessed only via an ISP that does not peer with us. ㅡ If some of your traffic is being served to users at ISPs that do not peer with us, there is a good chance it may be served from non-local routes. Despite being closer to one particular PoP you might find that your traffic is flowing through another one located further away. While performance for some of these customers may be reduced at times, all other Cloudflare benefits will work the same. ㅡ You can read more about this on our blog: The relative cost of bandwidth around the world ㅡ If you want to make sure you retain access to all Cloudflare transit providers worldwide, please upgrade to our Business or Enterprise Plan in your Cloudflare dashboard, under the Overview section.

**Comment by MattIPv4** [comment]
Closing, no further progress.
